# Generated by Django 3.2 on 2022-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo_colocacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo de Colocación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo de Envío'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='otros_costos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Costo Costos'),
        ),
    ]
